---

name: called-ai-pr-reviewer
on:
  workflow_call:
    secrets:
      token:
        required: true
      openai_api_key:
        required: true
permissions:
  contents: read
  pull-requests: write
jobs:
  review:
    if: (github.event.action == 'labeled' && github.event.label.name == 'ai review wanted') ||
        (github.event_name == 'pull_request_review_comment' && contains(github.event.pull_request.labels.*.name, 'ai review wanted'))
    runs-on: ubuntu-latest
    steps:
      - uses: coderabbitai/ai-pr-reviewer@latest
        env:
          GITHUB_TOKEN: ${{ secrets.token }}
          OPENAI_API_KEY: ${{ secrets.openai_api_key }}
        with:
          debug: false
          review_simple_changes: false
          review_comment_lgtm: true
          openai_light_model: gpt-4
          openai_heavy_model: gpt-4
          openai_timeout_ms: 1200000
          language: ja-JP
