---

name: called-preset-pr
on:
  workflow_call:
    secrets:
      token:
        required: true
      slack_id:
        required: true
      slack_webhook_url:
        required: true
jobs:
  set-assignees:
    runs-on: ubuntu-latest
    if: ${{ toJSON(github.event.pull_request.assignees) == '[]' && github.actor != 'dependabot[bot]' }}
    steps:
      - name: Set assignees
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.token }}
          script: |
            github.rest.issues.addAssignees({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              assignees: `${{ github.actor }}`
            });
  notification:
    runs-on: ubuntu-latest
    needs: [set-assignees]
    if: ${{ always() && github.actor != 'dependabot[bot]' }}
    steps:
      - name: Slack notification
        uses: slackapi/slack-github-action@v1.24.0
        with:
          payload: |
            {
              "text": "*Pull request opened*\n\n${{ github.event.pull_request.html_url }}",
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "${{ secrets.slack_id }}"
                  }
                },
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "*Pull request opened*\n\n${{ github.event.pull_request.html_url }}"
                  }
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.slack_webhook_url }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
