---

name: dependabot-auto-merge
on: pull_request_target
permissions:
  pull-requests: write
  contents: write
run-name: ${{ github.workflow }} (${{ github.ref_name }})
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false
jobs:
  call-dependabot-auto-merge:
    uses: ./.github/workflows/called-dependabot-auto-merge.yml
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
